name = input('Enter an employee: ')
company = input('Enter a company: ')
number_of_employees = int(input("Enter the number of employees: "))
average_monthly_fee = float(input("Enter the average monthly fee: "))
print(name + " works at the company " + company)
print("It has: ", number_of_employees, "employees. ")
print("The average monthly fee is: " + str(average_monthly_fee))
print("==============Check the data types below:===============")
print("The data type of the variable [name] is: ", type(name))
print("The data type of the variable [company] is: ", type(company))
print("The data type of the variable [number_of_employees] is: ", type(number_of_employees))
print("The data type of the variable [average_monthly_fee] is: ", type(average_monthly_fee))